apiVersion: apps/v1
kind: Deployment
metadata:
  name: oape-server
  labels:
    app: oape-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oape-server
  template:
    metadata:
      labels:
        app: oape-server
    spec:
      containers:
        - name: oape-server
          image: ghcr.io/shiftweek/oape-ai-e2e:latest
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 4Gi
          envFrom:
            - configMapRef:
                name: oape-server-config
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gcloud/application_default_credentials.json
          volumeMounts:
            - name: gcloud-adc
              mountPath: /secrets/gcloud
              readOnly: true
            - name: gh-token-shared
              mountPath: /shared
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
        - name: ghtoken-sidecar
          image: ghcr.io/shiftweek/oape-ai-e2e:latest
          command: ["/opt/ghtoken/token-refresh.sh"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: GH_APP_ID
              value: "3065249" # Replace with GitHub App ID if otherwise
            - name: GH_APP_PEM_FILE_PATH
              value: /secrets/gh-app/bot-key.pem
          volumeMounts:
            - name: gh-app-key
              mountPath: /secrets/gh-app
              readOnly: true
            - name: gh-token-shared
              mountPath: /shared
      volumes:
        - name: gcloud-adc
          secret:
            secretName: gcloud-adc-secret
        - name: gh-app-key
          secret:
            secretName: gh-app-secret
        - name: gh-token-shared
          emptyDir: {}
        - name: config
          configMap:
            name: oape-configs
---
apiVersion: v1
kind: Service
metadata:
  name: oape-server
spec:
  selector:
    app: oape-server
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
